name: go-1

services:
  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: auth-service
    environment:
      - AUTH_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - app-network

  tasks:
    build:
      context: .
      dockerfile: services/tasks/Dockerfile
    container_name: tasks-service
    environment:
      - TASKS_PORT=8082
      - AUTH_BASE_URL=http://auth:8081
    ports:
      - "8082:8082"
    depends_on:
      - auth
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
