{
 "title": "PZ4 Go App Monitoring",
 "tags": [
  "pz4",
  "go"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Общее число запросов",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(app_http_requests_total)" }
   ]
  },
  {
   "title": "Число ошибок",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "sum(app_http_errors_total)" }
   ]
  },
  {
   "title": "Активные запросы",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "app_active_requests" }
   ]
  },
  {
   "title": "Запросы по маршруту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (path) (app_http_requests_total)"
    }
   ]
  },
  {
   "title": "Средняя длительность HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(app_http_request_duration_seconds_sum[1m])) / sum(rate(app_http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Ошибки по коду ответа",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (status_code) (app_http_errors_total)"
    }
   ]
  },
  {
   "title": "Запросы по student_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (student_id) (app_student_requests_total)"
    }
   ]
  }
 ]
}