package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"example.com/pz12-rest-graphql/graph/model"
	"example.com/pz12-rest-graphql/internal/store"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	t := r.TaskSvc.Create(input.Title, input.Description)
	return toModelTask(t), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	t, err := r.TaskSvc.Update(id, input.Title, input.Description, input.Done)
	if err != nil {
		return nil, fmt.Errorf("task not found")
	}
	return toModelTask(t), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	ok, err := r.TaskSvc.Delete(id)
	if err != nil {
		return false, fmt.Errorf("task not found")
	}
	return ok, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	items := r.TaskSvc.List()
	out := make([]*model.Task, 0, len(items))
	for _, t := range items {
		out = append(out, toModelTask(t))
	}
	return out, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	t, err := r.TaskSvc.Get(id)
	if err != nil {
		return nil, err
	}
	if t == nil {
		return nil, nil
	}
	return toModelTask(t), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func toModelTask(t *store.Task) *model.Task {
	if t == nil {
		return nil
	}
	return &model.Task{
		ID:          t.ID,
		Title:       t.Title,
		Description: t.Description,
		Done:        t.Done,
	}
}
