FROM golang:1.25.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /tasks ./services/tasks/cmd/tasks

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /tasks .

EXPOSE 8082

ENV TASKS_PORT=8082
ENV AUTH_MODE=http
ENV AUTH_BASE_URL=http://localhost:8081

CMD ["./tasks"]
